// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function Functor(P) {
  return /* module */[/* f */P[0]];
}

function f(x) {
  return x;
}

function g(x) {
  return x;
}

var M = /* module */[
  /* f */f,
  /* g */g
];

var L = /* module */[/* f */f];

exports.Functor = Functor;
exports.M       = M;
exports.L       = L;
/* No side effect */
