// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function Make(Fst) {
  return (function (Snd) {
      var make = function (f, s) {
        return /* tuple */[
                f,
                s
              ];
      };
      var print = function (param) {
        return "(" + (Curry._1(Fst[/* print */0], param[0]) + (", " + (Curry._1(Snd[/* print */0], param[1]) + ")")));
      };
      return /* module */[
              /* make */make,
              /* print */print
            ];
    });
}

exports.Make = Make;
/* No side effect */
