// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                           = require("bs-platform/lib/js/curry.js");
var Pervasives                      = require("bs-platform/lib/js/pervasives.js");
var Repetition$ReasonmlDemoFunctors = require("./Repetition.bs.js");

var CountThree = /* module */[/* count */3];

var RepetitionThree = Repetition$ReasonmlDemoFunctors.Make(CountThree);

Pervasives.print_string(Curry._2(RepetitionThree[/* repeat */0], /* None */0, "abc\n"));

exports.CountThree      = CountThree;
exports.RepetitionThree = RepetitionThree;
/* RepetitionThree Not a pure module */
